# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171010_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='blog.Category'),
        ),
    ]
